version: '3'
services:
  jackblock-node:
    image: jb-alt:latest
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - "data:/data"
    command: node-template --chain local

volumes:
    data:
    