version: '3'
services:
  jackblock-node:
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
    image: tkodckr/jackblock-node:latest
    volumes:
      - "data:/data"
    command: node-template

volumes:
  data:
