version: '3.7'

services:
  jackblock-node:
    image: tkodckr/jackblock-node:latest
    container_name: "jackblock-node"
    restart: always
    depends_on:
      - "svg-bonanza"
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    volumes:
      - "data:/data"
    labels:
      - traefik.enable=true
      # RPC
      - traefik.http.routers.rpc.rule=Host(`rpc.jackblock.network`)
      - traefik.http.routers.rpc.entrypoints=websecure
      - traefik.http.routers.rpc.tls=true
      # Certificates RPC
      - traefik.http.routers.rpc.tls.certresolver=leresolver
      - traefik.http.routers.rpc.tls.domains[0].main=rpc.jackblock.network
      - traefik.http.services.svc-rpc.loadbalancer.server.port=9933
      - traefik.http.routers.rpc.service=svc-rpc

      # WSS
      - traefik.http.routers.ws.rule=Host(`ws.jackblock.network`)
      - traefik.http.routers.ws.entrypoints=websecure
      - traefik.http.routers.ws.tls=true
      # Certificates WSS
      - traefik.http.routers.ws.tls.certresolver=leresolver
      - traefik.http.routers.ws.tls.domains[0].main=ws.jackblock.network
      - traefik.http.services.svc-ws.loadbalancer.server.port=9944
      - traefik.http.routers.ws.service=svc-ws
      - traefik.http.routers.ws.middlewares=sslheader
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=wss,https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Ssl=on

    entrypoint: node-template
    # command for the boot node
    command: -lruntime=debug --rpc-external --ws-external --chain public --port 30333 --rpc-port 9933 --ws-port 9944 --validator --rpc-cors all --rpc-methods Unsafe --no-mdns --name jackblock-node-tko --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --node-key 36b2372af482746a4ddb6d5755f77c8487d7b92cf479a1dc84935ac071deadb4
    # command for every other node
    # command: -lruntime=debug --rpc-external --ws-external --chain public --port 30333 --rpc-port 9933 --ws-port 9944 --validator --rpc-cors all --rpc-methods Unsafe --bootnodes /ip4/54.253.234.233/tcp/30333/p2p/12D3KooWGkcu5myAw1TNDJMjaQr9pYisEuEkxg3USH5VARSXoYFK --no-mdns --name jackblock-node-rafal --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'

  
  svg-bonanza:
    image: tkodckr/svg-bonanza:latest
    container_name: "svg-bonanza"
    restart: always
    env_file: svg-bonanza.env
    ports:
      - "3000:3000"

  traefik:
    image: "traefik:2.4.8"
    container_name: "traefik"
    restart: always
    depends_on:
      - "jackblock-node"
      - "svg-bonanza"
    command:
      - --accesslog
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedHeaders.insecure=true
      - --entrypoints.websecure.http.tls.certResolver=leresolver
      - --entrypoints.websecure.http.tls.domains[0].main=jackblock.network
      - --entrypoints.websecure.http.tls.domains[0].sans=rpc.jackblock.network,ws.jackblock.network,www.jackblock.network
      - --certificatesResolvers.leresolver.acme.email=tomasz@kopacki.net
      - --certificatesResolvers.leresolver.acme.storage=/acme.json
      - --certificatesResolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
      - "./traefik/dynamic:/etc/traefik/dynamic"

volumes:
  data:
