blank_issues_enabled: true
contact_links:
  - name: Todo
    about: Create new todo for jackblock project
    url: https://github.com/korzewski/jackblock/issues/new?template=todo&projects=korzewski/jackblock/1
