name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [master, docker-build-optimised]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Define vars
        id: vars
        run: echo "::set-output name=commit_id::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 'nightly-2020-12-29'
          targets: 'wasm32-unknown-unknown'
      - name: Checkout the source code
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Check targets are installed correctly
        run: rustup target list --installed
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./scripts/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            tkodckr/jackblock-node:latest
            tkodckr/jackblock-node:${{ steps.vars.outputs.commit_id }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
