name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ 25-cloud-compatible-node ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 'nightly-2020-12-29'
          targets: 'wasm32-unknown-unknown'
      - name: Checkout the source code
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Check targets are installed correctly
        run: rustup target list --installed
      - name: Build optimized binary
        run: cargo build --release --verbose
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        run: |
          docker build . -f scripts/Dockerfile -t tkodckr/jackblock-node:latest
          docker push tkodckr/jackblock-node:latest